### ISSUE TITLE
leafEncodings not support tuple and array

### ISSUE THREAD

**Issue by vulh1209** [FantasyJony/openzeppelin-merkle-tree-go#1]
Hey FantasyJony,
I can't merkle data with leafEncodings 
 [‘address’, ‘uint88’, ‘uint88[]’, ‘uint128[]’]

**Comment by FantasyJony** [comment]
fixed in tag v1.1.1
example: https://github.com/FantasyJony/openzeppelin-merkle-tree-go/blob/main/standard_merkle_tree/openzeppelin_standard_tree_test.go#L393
