### ISSUE TITLE
throw error "abi: cannot use ptr as type uint8 as argument" when use uint8 in leafEncodings

### ISSUE THREAD

**Issue by vulh1209** [FantasyJony/openzeppelin-merkle-tree-go#2]
`package main

import (
	"fmt"

	smt "github.com/FantasyJony/openzeppelin-merkle-tree-go/standard_merkle_tree"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

func main() {
	values := [][]interface{}{
		{
            smt.SolAddress("0x1111111111111111111111111111111111111111"),
            smt.SolNumber("1"),
            smt.SolNumber("2"),
            smt.SolNumber("3"),
        },
		{
            smt.SolAddress("0x1111111111111111111111111111111111111111"),
            smt.SolNumber("0"),
            smt.SolNumber("2"),
            smt.SolNumber("1"),
        },
	}
	
	
	leafEncodings := []string{
		"address",
		"uint8",
		"uint88",
		"uint128",
	}

	tree, err := smt.Of(values, leafEncodings)
		handleError(err)
	fmt.Println("Root: ", hexutil.Encode(tree.GetRoot()))
}
`

Error log: 

`
 ➭ go run .
panic: abi: cannot use ptr as type uint8 as argument

goroutine 1 [running]:
main.handleError(...)
        /***/hello/main.go:44
main.main()
        /***/hello/main.go:37 +0x568
exit status 2
`

**Comment by FantasyJony** [comment]
fixed v1.1.2
test: https://github.com/FantasyJony/openzeppelin-merkle-tree-go/blob/main/standard_merkle_tree/openzeppelin_standard_tree_test.go#L471
